comment/urls.py
from django.conf.urls import patterns, url, include

from comment import views, updateCommentData

urlpatterns = patterns('',
	url(r'^super/(?P<comment_id>\d+)/$', views.super),
	url(r'^desuper/(?P<comment_id>\d+)/$', views.deSuper),
	url(r'^lecture/(?P<lecture_id>\d+)/$', views.commentLecture),
	# url(r'^gettoday/(?P<check_code>.*)/$', views.getTodayComments),
	url(r'^update/(?P<mode>[a-z]+)/$', updateCommentData.updateCommentData),
)

gossip/urls.py
from django.conf.urls import patterns, url, include

from gossip import views

urlpatterns = patterns('',
	url(r'^$', views.gossip, name='gossip'),
	url(r'^record/$', views.recordGossip),
	url(r'^(?P<super_action>super|desuper)/(?P<gossip_id>\d+)/$', views.superGossip),
	url(r'^getgossips/(?P<start>\d+)/(?P<end>\d+)/$', views.getGossips),
	# url(r'^(?P<user_id>\d+)/$', views.userpage, name='userpage'),
	# url(r'^sign/$', views.sign, name='sign'),
	# url(r'^changepassword/$', views.changepassword),
	# url(r'^login/$', views.login, name='login'),
	# url(r'^requestweightdata/(?P<user_id>\d+)/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', views.requestweightdata),
	# url(r'^submit/$', views.submit, name='submit')
)

lecture/urls.py
from django.conf.urls import patterns, url, include

from lecture import views

urlpatterns = patterns('',
	url(r'^(?P<lecture_id>\d+)/$', views.getLecture, name='lecture'),
	url(r'^getdata/(?P<lecture_id>\d+)/$', views.getLectureData),
	url(r'^recordscore/(?P<lecture_id>\d+)/$', views.recordStudentScore),
	url(r'^recordlevel/(?P<lecture_id>\d+)/$', views.recordLevel),
	url(r'^recordall/(?P<lecture_id>\d+)/$', views.recordAll),
	url(r'^getcourses/(?P<start>\d+)/(?P<end>\d+)/$', views.getCourses),
	url(r'^courselist/$', views.courselist),
	url(r'^test/$', views.test),
	#url(r'^getlecturedata/(?P<lecture_id>\d+)/$', views.getLectureData),
)

login/urls.py
from django.conf.urls import patterns, url, include

from login import views

urlpatterns = patterns('',
	url(r'^$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^register/$', views.register, name='register'),
	url(r'^register/(?P<key>account|name)/(?P<content>.+)/$', views.checkAccountName),
	url(r'^register/checkuser/(?P<user_id>\d+)/(?P<check_code>\d+)/$', views.regCheckUser),
	url(r'^setpassword/$', views.setPassword),
	url(r'^setpassword/checkuser/(?P<user_id>\d+)/(?P<check_code>\d+)/$', views.setPwdCheckUser),
	url(r'^setpassword/newpassword/$', views.setNewPassword),
	url(r'^(?P<user_id>\d+)/$', views.userpage, name='userpage'),
	url(r'^sign/$', views.sign, name='sign'),
	url(r'^changepassword/$', views.changepassword),
	url(r'^test/$', views.test),
	# url(r'^login/$', views.login, name='login'),
	# url(r'^requestweightdata/(?P<user_id>\d+)/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', views.requestweightdata),
	# url(r'^submit/$', views.submit, name='submit')
)

comment/models.py
from django.db import models

# Create your models here.
from login.models import User
from lecture.models import LectureComment

class MessageOfCommentSuper(models.Model):
	class Meta:
		db_table = "messageOfCommentSuper"

	user = models.ForeignKey(User, db_column="user_id")
	lecture_comment = models.ForeignKey(LectureComment, db_column="lecture_comment_id")
	super_added = models.IntegerField(default=1, db_column="super_added")

lecture/models.py
from django.db import models
from login.models import User
from userpage.formatTime import formatTime

class Course(models.Model):
	class Meta:
		db_table = "course"

	name = models.CharField(max_length = 50, db_column = "name")
	number = models.CharField(max_length = 10, db_column = "number")
	credit = models.FloatField(default = 0, db_column = "credit")
	school = models.CharField(max_length = 50, db_column = "school")
	view_time = models.IntegerField(default = 0, db_column = "view_time")
	name_pinyin = models.CharField(max_length = 50, db_column = "name_pinyin")
	name_forsearch = models.CharField(max_length = 50, db_column = "name_forsearch")
	category = models.CharField(max_length = 50, db_column = "category")

	def getDict(self, id=True, name=True, number=True, credit=True, school=True, category=True):
		ret = {}
		if id: 			ret['id'] = self.id
		if name: 		ret['name'] = self.name
		if number: 		ret['number'] = self.number
		if credit:		ret['credit'] = self.credit
		if school: 		ret['school'] = self.school
		if category: 	ret['category'] = self.category

		return ret

class Professor(models.Model):
	class Meta:
		db_table = "professor"

	name = models.CharField(max_length = 50, db_column = "name")
	number = models.CharField(max_length = 20, db_column = "number")
	title = models.CharField(max_length = 50, db_column = "title")

	def getDict(self, id=True, name=True, number=False, title=False):
		ret = {}
		if id: 			ret['id'] = self.id
		if name: 		ret['name'] = self.name
		if number: 		ret['number'] = self.number
		if title:		ret['title'] = self.title

		return ret

class Lecture(models.Model):
	class Meta:
		db_table = "lecture"
		ordering = ["-level"]

	course = models.ForeignKey(Course, db_column = "course_id")
	professor = models.ForeignKey(Professor, db_column = "professor_id")
	student_score = models.FloatField(default = 0, db_column = "student_score")
	level = models.FloatField(default = 0, db_column = "level")
	student_score_number = models.IntegerField(default = 0, db_column = "student_score_number")
	level_number = models.IntegerField(default = 0, db_column = "level_number")
	level_1_number = models.IntegerField(default = 0, db_column = "level_1_number")
	level_2_number = models.IntegerField(default = 0, db_column = "level_2_number")
	level_3_number = models.IntegerField(default = 0, db_column = "level_3_number")
	level_4_number = models.IntegerField(default = 0, db_column = "level_4_number")
	level_5_number = models.IntegerField(default = 0, db_column = "level_5_number")

	def getDict(self, id=True, student_score=True, level=True, student_score_number=True, level_number=True):
		ret = {}
		if id: 						ret['id'] = self.id
		if student_score: 			ret['student_score'] = self.student_score
		if level: 					ret['level'] = self.level
		if student_score_number: 	ret['student_score_number'] = self.student_score_number
		if level_number:
			ret['level_number'] = self.level_number
			ret['level_1_number'] = self.level_1_number
			ret['level_2_number'] = self.level_2_number
			ret['level_3_number'] = self.level_3_number
			ret['level_4_number'] = self.level_4_number
			ret['level_5_number'] = self.level_5_number

		return ret

class LectureComment(models.Model):
	class Meta:
		db_table = "lectureComment"
		ordering = ["-rank_score"]

	lecture = models.ForeignKey(Lecture, db_column = "lecture_id")
	user = models.ForeignKey(User, db_column = "user_id")
	content = models.TextField(db_column = "content")
	super_weight = models.FloatField(default = 0.0, db_column = "super_weight")
	super_number = models.IntegerField(default = 0, db_column = "super_number")
	rank_score = models.FloatField(default = 0.0, db_column = "rank_score")
	need_recompute = models.BooleanField(default=True, db_column = "need_recompute")
	time = models.DateTimeField(auto_now_add = True, db_column = "time")

	def getDict(self, id=True, content=True, super_number=True, time=True, user=False):
		ret = {}
		if id: 			ret['id'] = self.id
		if content:		ret['content'] = self.content
		if super_number:ret['super_number'] = self.super_number
		if time:		ret['time'] = formatTime(self.time)
		if user:		ret['user'] = self.user.getDict()

		return ret

class LectureCommentSuperRecord(models.Model):
	class Meta:
		db_table = "lectureCommentSuperRecord"

	lecture_comment = models.ForeignKey(LectureComment, db_column = "lectureComment_id")
	user = models.ForeignKey(User, db_column = "user_id")
	time = models.DateTimeField("data published", db_column = "time")

class LectureLevelRecord(models.Model):
	class Meta:
		db_table = "lectureLevelRecord"

	lecture = models.ForeignKey(Lecture, db_column = "lecture_id")
	user = models.ForeignKey(User, db_column = "user_id")
	level = models.SmallIntegerField(db_column = "level")
	time = models.DateTimeField("data published", db_column = "time")

class LectureStudentScoreRecord(models.Model):
	class Meta:
		db_table = "lectureStudentScoreRecord"

	lecture = models.ForeignKey(Lecture, db_column = "lecture_id")
	user = models.ForeignKey(User, db_column = "user_id")
	score = models.SmallIntegerField(db_column = "score")
	time = models.DateTimeField("data published", db_column = "time")

class UserLectureCollection(models.Model):
	class Meta:
		db_table = "userLectureCollection"
		ordering = ["-time"]

	user = models.ForeignKey(User, db_column = "user_id")
	lecture = models.ForeignKey(Lecture, db_column = "lecture_id")
	time = models.DateTimeField("data published", db_column = "time")

templates/lecture/courselist.html
{% load staticfiles %}
{% load login_extras %}
<!DOCTYPE html>
<html lang="zh">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="SJTU Course————最真实可靠的交大课程信息交流平台！">
    <meta name="author" content="lyw">
    <link href="{% static 'img/icon2.jpg' %}" rel="icon">

		<title>课程点评网</title>

		<!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="//oss.maxcdn.com/libs/html5shiv/3.6.2/html5shiv.js"></script>
    <script src="../../docs-assets/js/respond.min.js"></script>
    <![endif]-->
	</head>

	<body>
    {% csrf_token %}
    <div class="container">
      <nav class="navbar navbar-inverse navbar-fixed-top" style="max-width:1140px;MARGIN-RIGHT: auto;MARGIN-LEFT: auto;TEXT-ALIGN: center;">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navcol">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/" style=" margin-top:-3px;">
            <img src="{% static 'img/logo_small.png' %}" border="0" width="78" height="30" style="margin-top:-3px;">
              课程点评网
          </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navcol">
          <ul class="nav navbar-nav">
            <!-- <li><a href="#">课程排行</a></li>
            <li><a href="#">课程交易</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">课程分类 <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">人文通识</a></li>
                <li><a href="#">社科通识</a></li>
                <li><a href="#">自然通识</a></li>
                <li class="divider"></li>
                <li><a href="#">必修课</a></li>
                <li class="divider"></li>
                <li><a href="#">任选课</a></li>
              </ul>
            </li> -->
          </ul>
          <!-- <form class="navbar-form navbar-left">
            <div class="form-group dropdown" style="width:400px;">
              <input type="text" class="form-control" id="search" autocomplete="off" placeholder="来这里找课！">
              <ul class="dropdown-menu" id="complete" style="width:100%;margin-top:-1px;text-align:left;"></ul>
            </div>
            <button type="submit" id="submit" class="btn btn-default">搜索</button>
          </form> -->
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href={% if u.messageofcommentsuper_set.all.count %}"#" class="dropdown-toggle" data-toggle="dropdown"{% else %}"/"{% endif %} style="white-space:pre;"><span class="glyphicon glyphicon-user"></span>  {{ u.name }} <span class="badge" style="background-color:#FF7744 ;">{% if u.messageofcommentsuper_set.all.count %}{{ u.messageofcommentsuper_set.all.count }}{% endif %}</span></a>
              {% if u.messageofcommentsuper_set.all.count %}
              <ul class="dropdown-menu" style="width:350px;margin-top:4px;max-height:400px;overflow:auto;overflow-x:hidden;">
                {% for message in u.messageofcommentsuper_set.all reversed %}
                <li class="dropdown-header" style="text-align:left;">
                  {{ message.lecture_comment.lecture.professor.name|truncatechars:10 }} 《{{ message.lecture_comment.lecture.course.name|truncatechars:12 }}》<p style="text-align:right;margin-top:-1.5em"><span class="badge" style="background-color:#00DD00;">有用 +{{ message.super_added }}</span></p>
                </li>
                <li>
                  <a href="/userpage/checksupermessage/{{ message.id }}/"><blockquote style="margin-bottom:-12px;margin-top:-12px;"><p style="text-align:left;font-size:small;">{{ message.lecture_comment.content|truncatechars:20 }}</p><small style="text-align:right;">{{ message.lecture_comment.time|formatTime }}</small></blockquote></a>
                </li>
                <li class="divider"></li>
                {% endfor %}
                <li>共 {{u.messageofcommentsuper_set.all.count}} 条</li>
              </ul>
              {% endif %}
            </li>
            <li><a href="javascript:void(0);" onclick="$('#sName').modal('show');">修改昵称</a></li>
            <li><a href="/setpassword/">修改密码</a></li>
            <li><a href="/logout/">退出</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>

      <!-- extra search -->
      <div class="modal fade" id="eSearch" tabindex="-1">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
              <button type="button" class="btn btn-primary" data-dismiss="modal">确定</button>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->

      <!-- set name -->
      <div class="modal fade" id="sName" tabindex="-1">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title">修改昵称</h4>
            </div>
            <div class="modal-body">
              <form class="form-horizontal" role="form">
                <div class="form-group">
                  <label class="col-xs-2 control-label">旧昵称</label>
                  <div class="col-xs-10">
                    <p class="form-control-static">{{ u.name }}</p>
                  </div>
                </div>
                <div class="form-group">
                  <label for="newname" class="col-xs-2 control-label">新昵称<span id="helpname" class="help-block"></span></label>
                  <div class="col-xs-10 enter">
                    <input type="text" class="form-control" id="newname" placeholder="新昵称" autocomplete="off">
                    <label for="name" id="nm_prompt"></label>
                  </div>
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-primary" onclick="setname_post()">确定</button>
              <button type="button" class="btn btn-primary" data-dismiss="modal">取消</button>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->

      <div class="col-xs-12" style="margin-top:70px;">
        <div class="row">
          <div class="col-xs-3" style="text-align:left;position:fixed;width:300px;"> 
            <ul class="nav nav-pills nav-stacked">
              <li class="active success" style="background-color:#F2F2F2;border: 0px solid #DCDCFA;border-radius: 6px;">
                <a data-toggle="tab" href="#renwen" data-placement="right"><h4><strong>人文学科</strong></h4></a>
              </li>
              <li style="background-color:#F2F2F2;border: 0px solid #DCDCFA;border-radius: 6px;">
                <a data-toggle="tab" href="#sheke" data-placement="right"><h4><strong>社会科学</strong></h4></a>
              </li>
              <li style="background-color:#F2F2F2;border: 0px solid #DCDCFA;border-radius: 6px;">
                <a data-toggle="tab" href="#ziran" data-placement="right"><h4><strong>自然科学与工程技术</strong></h4></a>
              </li>
              <li style="background-color:#F2F2F2;border: 0px solid #DCDCFA;border-radius: 6px;">
                <a data-toggle="tab" href="#shuxue" data-placement="right"><h4><strong>数学或逻辑学</strong></h4></a>
              </li>
            </ul>
          </div>

          <div class="col-sm-offset-3 col-xs-9">
            <div class="tab-content">
              <div class="tab-pane fade in active" id="renwen">
                <div class="panel panel-primary">
                  <div class="panel-heading">
                    
                  </div>
                  <div class="panel-body">
                    <ul class="list-group">
                      {% for cc in c %}
                      {% ifequal cc.category "人文学科" %}
                      <li class="list-group-item" style="border-color:#AAAAAA">
                        <a href="#" onclick="search_get({{ cc.id }})">{{ cc.name }}</a>
                      </li>
                      {% endifequal %}
                      {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade in" id="sheke">
               <div class="panel panel-primary">
                  <div class="panel-heading">
                    
                  </div>
                  <div class="panel-body">
                    <ul class="list-group">
                      {% for cc in c %}
                      {% ifequal cc.category "社会科学" %}
                      <li class="list-group-item" style="border-color:#AAAAAA">
                        <a href="#" onclick="search_get({{ cc.id }})">{{ cc.name }}</a>
                      </li>
                      {% endifequal %}
                      {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade in" id="ziran">
                <div class="panel panel-primary">
                  <div class="panel-heading">
                    
                  </div>
                  <div class="panel-body">
                    <ul class="list-group">
                      {% for cc in c %}
                      {% ifequal cc.category "自然科学与工程技术" %}
                      <li class="list-group-item" style="border-color:#AAAAAA">
                        <a href="#" onclick="search_get({{ cc.id }})">{{ cc.name }}</a>
                      </li>
                      {% endifequal %}
                      {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade in" id="shuxue">
                <div class="panel panel-primary">
                  <div class="panel-heading">
                    
                  </div>
                  <div class="panel-body">
                    <ul class="list-group">
                      {% for cc in c %}
                      {% ifequal cc.category "数学或逻辑学" %}
                      <li class="list-group-item" style="border-color:#AAAAAA">
                        <a href="#" onclick="search_get({{ cc.id }})">{{ cc.name }}</a>
                      </li>
                      {% endifequal %}
                      {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div><!-- container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/myjquery.js' %}"></script>
    <script src="{% static 'js/search.js' %}"></script>
    <script>
    </script>
	</body>
</html>

templates/lecture/test.html
{% load staticfiles %}
<html lang="en-CN">
<head>
	<meta charset="utf-8">
	<meta name="author" content="jt">	

	<title>课程点评网</title>

	<script type="text/javascript" src="{% static 'js/jquery-1.10.2.min.js' %}"></script>

	<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
	<link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
	  
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<body>
User influence: <br/>
user name: {{ u.name }}<br/>
user influence factor: {{ user_influence_factor }}<br/>
user rank: {{ user_rank }}<br/>
<br/>
<br/>

Your message: <br/>
{% for message in u.messageofcommentsuper_set.all %}
	{{ message.id}}__
	{{ message.lecture_comment.lecture.course.name }}__
	{{ message.lecture_comment.lecture.professor.name }}__
	{{ message.lecture_comment.content }}__
	add {{ message.super_added }} SUPERS<br/>
{% endfor %}
<br/>
<br/>

System Achievement: {{ sys_achievement }}<br/>
<br/>
<br/>

Your comment: <br/>
total {{ u.lecturecomment_set.all.count }} comments<br/>
list 3 of them <br/>
<table class="table table-striped">
	<thead></thead>
	<tbody>
		{% for comment in u.lecturecomment_set.all|slice:":3" %}
		<tr>
			<th>
				{{ comment.user.name }}<br/>
				{{ comment.lecture.course.name }}<br/>
				{{ comment.lecture.professor.name }}
			</th>
			<th>
				<p>{{ comment.content }}</p>
				<ul class="breadcrumb">
					<li style="margin-right:40%;">
						{{ comment.time|date:"Y-m-d H:i:s" }}
					</li>
					<li>
						{{ comment.super_number }} SUPERs
					</li>
					<li>
						rank_score: {{ comment.rank_score }}
					</li>
				</ul>
				<p><br/></p>
			</th>
		</tr>
		{% empty %}
		<p>You haven't make a comment</p>
		{% endfor %}
	</tbody>
</table>
<br/>
<br/>

Change Lecture: <br/>
{% for l in lectures %}
	{{ l.course.name }}__
	{{ l.professor.name }}__
	{{ l.level }}__
	/lecture/{{ l.id }}<br/>
{% endfor %}
<br/>
<br/>
Your lecture collection: <br/>
{% for collectionrecord in u.userlecturecollection_set.all|slice:":3" %}
	{{ collectionrecord.lecture.course.name }}__
	{{ collectionrecord.lecture.professor.name }}__
	{{ collectionrecord.lecture.id }}<br/>
	{% for c in collectionrecord.lecture.lecturecomment_set.all|slice:":1" %}
		_________most popular comment: {{ c.user.name }}__{{ c.content }}__super number: {{ c.super_number }}<br/>
	{% empty %}
		there are no comment in this lecture.<br/>
	{% endfor %}
	<br/>
{% empty %}
	Your haven't collected any lecture<br/>
{% endfor %}


</body>